### ISSUE TITLE
Plugin doesn't work in 1.29.1

### ISSUE THREAD

**Issue by RADt29** [DJDavid98/bsrpc#7] opened 2023-09-23 11:55 UTC
while having the plugin installed on 1.29.1 discord still displays the default rich presence 
![image](https://github.com/DJDavid98/bsrpc/assets/115356338/a15a6cfb-70e2-4693-9fa2-bcda5776e8be)

at first i taught it was other plugins that maybe prevented this from working but even from a fresh reinstall it still doesnt work
![image](https://github.com/DJDavid98/bsrpc/assets/115356338/3c3f33e3-8973-4c72-8ae0-ff4dc594713f)

is the plugin outdated or am i missing something?

**Comment by AwkwardAiden** [comment] 2023-09-23 19:26
My friend is also having this issue. However, while we have both installed the mod and all of its prerequisites today, mine is working but his is not. All I can assume is that there is some other mod that is preventing this mod from being detected - check DiscordCore in your mod settings in game and see if the Rich Presence mod is being detected in the priorities. With me and my friend, mine is being detected, but my friend's isn't being detected at all. I have no clue what could be causing this, but it might make it easier to narrow down.

**Comment by Mystrik** [comment] 2023-09-25 17:18
I'm having the same issue, using all the marked dependencies at the specific versions, nothing is showing up ingame or in my status.

**Comment by DJDavid98** [comment] 2023-09-25 17:23
Please check your game logs, I am actually unable to help you without it, as it definitely works for me. In the `Logs` folder of the game there is supposed to be a `_latest.log` that you can open with any text editor, and searching for `bsrpc` in that file should give you an idea what is going on. If you cannot figure it out on your own, then post the whole log as-is in your comment.

**Comment by Mystrik** [comment] 2023-09-25 17:39
Hi, the only two lines that mention bsrpc say this in order:

[DEBUG @ 11:47:56 | IPA/Loader] Adding info for bsrpc.dll
[WARNING @ 11:48:07 | IPA/Loader] Dependency 'DataPuller' for 'bsrpc' previously ignored; ignoring 'bsrpc'

I'm thinking maybe datapuller is missing a libs file that I never downloaded because I got it for the first time off of this page? I'm leaving to go to work right now so I'll test that in a bit.
(log included why not)
[_latest.log](https://github.com/DJDavid98/bsrpc/files/12718015/_latest.log)

**Comment by Mystrik** [comment] 2023-09-25 22:31
Ok I got it working after I opened modassistant and just installed DataPuller, which also gave me the requirements for it. The one I was missing was WebSocketSharp

DataPuller Dependencies:
BSIPA ^4.2.2
BeatSaverSharp ^3.4.2
WebsocketSharp ^1.0.4
SongCore ^3.9.5
SongDetailsCache ^1.2.1
SiraUtil ^3.0.5

**Comment by DJDavid98** [comment] 2023-12-03 14:27
Since the mod is confirmed working on this game version I am closing this issue.

**Closed by DJDavid98** 2023-12-03 14:27 UTC
